- exp_name: TSP
  dataset: random
  distance_type: GEO
  device: cuda:0
  num_nodes: [100,200,500,800,1000]
  num_times: 100
  seed: 42
  configs: ["CLASSIC","PVAR", "PVAR_PNODE"]
  make_inference: True
  generate_dataset: True
  read_seed: False
